@Evolutio.API_HostAddress = https://localhost:7144/api
@contentType = application/json

### Health check
GET {{Evolutio.API_HostAddress}}/health
Accept: {{contentType}}
###
### API check
GET {{Evolutio.API_HostAddress}}/health/test
Accept: {{contentType}}
###

